/**
 * Calendar Action Types
 */
export const GET_ALL_EVENTS = "GET_ALL_EVENTS";
export const GET_ALL_EVENTS_SUCCESS = "GET_ALL_EVENTS_SUCCESS";
export const GET_ALL_EVENTS_FAILURE = "GET_ALL_EVENTS_FAILURE";



export const ON_CHANGE_ADD_EVENT = "ON_CHANGE_ADD_EVENT";
export const ADD_EVENT = "ADD_EVENT";
export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS";
export const ADD_EVENT_FAILURE = "ADD_EVENT_FAILURE";

export const ON_CHANGE_UPDATE_EVENT = "ON_CHANGE_UPDATE_EVENT";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const UPDATE_EVENT_FAILURE = "UPDATE_EVENT_FAILURE";

export const DELETE_EVENT = "DELETE_EVENT";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAILURE = "DELETE_EVENT_FAILURE";

export const GET_EVENT_FAILURE = "GET_EVENT_FAILURE"
/**
 * State Changes
 */
export const CHANGE_DAY_VIEW = "CHANGE_DAY_VIEW";
export const CHANGE_EVENT_VIEW = "CHANGE_EVENT_VIEW";
export const CHANGE_CALENDAR_VIEW = "CHANGE_CALENDAR_VIEW";
export const SHOW_SELECTED_SLOT = "SHOW_SELECTED_SLOT";
export const HIDE_SELECTED_SLOT = "HIDE_SELECTED_SLOT";
export const SHOW_SELECTED_EVENT = "SHOW_SELECTED_EVENT";
export const SHOW_CREATE_EVENT = "SHOW_CREATE_EVENT";
export const HIDE_CREATE_EVENT = "HIDE_CREATE_EVENT";
export const SHOW_UPDATE_EVENT = "SHOW_UPDATE_EVENT";
