/**
 * Hierarchy Action Types
 */
export const GET_ALL_HIERARCHIES = "GET_ALL_HIERARCHIES";
export const GET_ALL_HIERARCHIES_SUCCESS = "GET_ALL_HIERARCHIES_SUCCESS";

export const ADD_HIERARCHY = "ADD_HIERARCHY";
export const ADD_HIERARCHY_SUCCESS = "ADD_HIERARCHY_SUCCESS";
export const ADD_HIERARCHY_FAILURE = "ADD_HIERARCHY_FAILURE";

export const ON_CHANGE_UPDATE_HIERARCHY = "ON_CHANGE_UPDATE_HIERARCHY";
export const UPDATE_HIERARCHY = "UPDATE_HIERARCHY";
export const UPDATE_HIERARCHY_SUCCESS = "UPDATE_HIERARCHY_SUCCESS";
export const UPDATE_HIERARCHY_FAILURE = "UPDATE_HIERARCHY_FAILURE";

export const DELETE_HIERARCHY = "DELETE_HIERARCHY";
export const DELETE_HIERARCHY_SUCCESS = "DELETE_HIERARCHY_SUCCESS";
export const DELETE_HIERARCHY_FAILURE = "DELETE_HIERARCHY_FAILURE";

export const GET_HIERARCHY_FAILURE = "GET_HIERARCHY_FAILURE";

//State Changes
export const CHANGE_SELECTED_GROUP_HIERARCHIES = "CHANGE_SELECTED_GROUP_HIERARCHIES";