/**
 * Role Action Types
 */
export const GET_ALL_ROLES = "GET_ALL_ROLES";
export const GET_ALL_ROLES_SUCCESS = "GET_ALL_ROLES_SUCCESS";

export const ADD_ROLE = "ADD_ROLE";
export const ADD_ROLE_SUCCESS = "ADD_ROLE_SUCCESS";
export const ADD_ROLE_FAILURE = "ADD_ROLE_FAILURE";

export const ON_CHANGE_UPDATE_ROLE = "ON_CHANGE_UPDATE_ROLE";
export const ON_CHANGE_UPDATE_ROLE_RIGHTS = "ON_CHANGE_UPDATE_ROLE_RIGHTS";
export const UPDATE_ROLE = "UPDATE_ROLE";
export const UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS";
export const UPDATE_ROLE_FAILURE = "UPDATE_ROLE_FAILURE";

export const DELETE_ROLE = "DELETE_ROLE";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const DELETE_ROLE_FAILURE = "DELETE_ROLE_FAILURE";

export const GET_ROLE_FAILURE = "GET_ROLE_FAILURE";

//State Changes
export const CHANGE_SELECTED_ROLE = "CHANGE_SELECTED_ROLE";
export const CHANGE_SELECTED_ACCESS_RIGHTS_CATEGORY = "CHANGE_SELECTED_ACCESS_RIGHTS_CATEGORY";
export const CHANGE_SELECTED_GROUP_ROLE = "CHANGE_SELECTED_GROUP_ROLE";