/**
 * Credit Note Actions
 */
// List
export const CREDIT_NOTE_LIST_DROPDOWN = "CREDIT_NOTE_LIST_DROPDOWN";
export const CHANGE_CREDIT_NOTE_LIST_VIEW = "CHANGE_CREDIT_NOTE_LIST_VIEW";
export const GET_CREDIT_NOTE_FAILURE = "GET_CREDIT_NOTE_FAILURE";
export const GET_CREDIT_NOTE_SUCCESS = "GET_CREDIT_NOTE_SUCCESS";
export const GET_ALL_CREDIT_NOTE = "GET_ALL_CREDIT_NOTE";
export const GET_MY_CREDIT_NOTE = "GET_MY_CREDIT_NOTE";
export const GET_OPEN_CREDIT_NOTE = "GET_OPEN_CREDIT_NOTE";
export const GET_CLOSED_CREDIT_NOTE = "GET_CLOSED_CREDIT_NOTE";

// View
export const GET_SINGLE_CREDIT_NOTE = "GET_SINGLE_CREDIT_NOTE";
export const GET_SINGLE_CREDIT_NOTE_SUCCESS = "GET_SINGLE_CREDIT_NOTE_SUCCESS";
export const CLEAR_SINGLE_CREDIT_NOTE = "CLEAR_SINGLE_CREDIT_NOTE";
