/**
 * Invoice Actions
 */
// List
export const INVOICE_LIST_DROPDOWN = "INVOICE_LIST_DROPDOWN";
export const TOGGLE_INVOICE_SUMMARY = "TOGGLE_INVOICE_SUMMARY";
export const CHANGE_INVOICE_LIST_VIEW = "CHANGE_INVOICE_LIST_VIEW";
export const GET_INVOICE_FAILURE = "GET_INVOICE_FAILURE";
export const GET_INVOICE_SUCCESS = "GET_INVOICE_SUCCESS";
export const GET_ALL_INVOICE = "GET_ALL_INVOICE";
export const GET_MY_INVOICE = "GET_MY_INVOICE";
export const GET_OPEN_INVOICE = "GET_OPEN_INVOICE";
export const GET_CLOSED_INVOICE = "GET_CLOSED_INVOICE";

// List Summary
export const GET_INVOICE_SUMMARY = "GET_INVOICE_SUMMARY";
export const GET_INVOICE_SUMMARY_SUCCESS = "GET_INVOICE_SUMMARY_SUCCESS";
export const GET_INVOICE_SUMMARY_FAILURE = "GET_INVOICE_SUMMARY_FAILURE";

// View
export const GET_SINGLE_INVOICE = "GET_SINGLE_INVOICE";
export const GET_SINGLE_INVOICE_SUCCESS = "GET_SINGLE_INVOICE_SUCCESS";
export const CLEAR_SINGLE_INVOICE = "CLEAR_SINGLE_INVOICE";
