/**
 * Quotation Actions
 */
// List
export const QUOTATION_LIST_DROPDOWN = "QUOTATION_LIST_DROPDOWN";
export const TOGGLE_QUOTATION_SUMMARY = "TOGGLE_QUOTATION_SUMMARY";
export const CHANGE_QUOTATION_LIST_VIEW = "CHANGE_QUOTATION_LIST_VIEW";
export const GET_QUOTATION_FAILURE = "GET_QUOTATION_FAILURE";
export const GET_QUOTATION_SUCCESS = "GET_QUOTATION_SUCCESS";
export const GET_ALL_QUOTATION = "GET_ALL_QUOTATION";
export const GET_MY_QUOTATION = "GET_MY_QUOTATION";
export const GET_OPEN_QUOTATION = "GET_OPEN_QUOTATION";
export const GET_CLOSED_QUOTATION = "GET_CLOSED_QUOTATION";

// List Summary
export const GET_QUOTE_SUMMARY = "GET_QUOTE_SUMMARY";
export const GET_QUOTE_SUMMARY_SUCCESS = "GET_QUOTE_SUMMARY_SUCCESS";
export const GET_QUOTE_SUMMARY_FAILURE = "GET_QUOTE_SUMMARY_FAILURE";

// View
export const GET_SINGLE_QUOTATION = "GET_SINGLE_QUOTATION";
export const GET_SINGLE_QUOTATION_SUCCESS = "GET_SINGLE_QUOTATION_SUCCESS";
export const CLEAR_SINGLE_QUOTATION = "CLEAR_SINGLE_QUOTATION";
