/**
 * App Redux Action Types
 */
export const COLLAPSED_SIDEBAR = "COLLAPSED_SIDEBAR";
export const DARK_MODE = "DARK_MODE";
export const BOXED_LAYOUT = "BOXED_LAYOUT";
export const RTL_LAYOUT = "RTL_LAYOUT";
export const MINI_SIDEBAR = "MINI_SIDEBAR";
export const SEARCH_FORM_ENABLE = "SEARCH_FORM_ENABLE";
export const CHANGE_THEME_COLOR = "CHANGE_THEME_COLOR";
export const TOGGLE_SIDEBAR_IMAGE = "TOGGLE_SIDEBAR_IMAGE";
export const SET_SIDEBAR_IMAGE = "SET_SIDEBAR_IMAGE";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const START_USER_TOUR = "START_USER_TOUR";
export const STOP_USER_TOUR = "STOP_USER_TOUR";
export const TOGGLE_DARK_SIDENAV = "TOGGLE_DARK_SIDENAV";

/**
 * Calendar Actions
 */
export const GET_ALL_EVENTS = "GET_ALL_EVENTS";
export const GET_MY_EVENTS = "GET_MY_EVENTS";
export const CHANGE_DAY_VIEW = "CHANGE_DAY_VIEW";
export const CHANGE_EVENT_VIEW = "CHANGE_EVENT_VIEW";
export const CHANGE_CALENDAR_VIEW = "CHANGE_CALENDAR_VIEW";
export const SHOW_SELECTED_SLOT = "SHOW_SELECTED_SLOT";
export const HIDE_SELECTED_SLOT = "HIDE_SELECTED_SLOT";
export const SHOW_SELECTED_EVENT = "SHOW_SELECTED_EVENT";
export const SHOW_CREATE_EVENT = "SHOW_CREATE_EVENT";
export const HIDE_CREATE_EVENT = "HIDE_CREATE_EVENT";
export const SHOW_UPDATE_EVENT = "SHOW_UPDATE_EVENT";

/**
 * Users Actions
 */
export const GET_ALL_USERS = "GET_ALL_USERS";
export const SHOW_ADD_USER = "SHOW_ADD_USER";
export const HIDE_ADD_USER = "HIDE_ADD_USER";


/**
 * Lead Actions
 */
export const CHANGE_LEAD_VIEW = "CHANGE_LEAD_VIEW";
export const SHOW_ALL_LEADS = "SHOW_ALL_LEADS";
export const SHOW_MY_LEADS = "SHOW_MY_LEADS";
export const SHOW_OPEN_LEADS = "SHOW_OPEN_LEADS";
