/**
 * Account Actions
 */
// List
export const TOGGLE_ACCOUNT_SUMMARY = "TOGGLE_ACCOUNT_SUMMARY";
export const CHANGE_ACCOUNT_LIST_VIEW = "CHANGE_ACCOUNT_LIST_VIEW";
export const GET_ACCOUNT_FAILURE = "GET_ACCOUNT_FAILURE";
export const GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS";
export const GET_ALL_ACCOUNT = "GET_ALL_ACCOUNT";
export const GET_MY_ACCOUNT = "GET_MY_ACCOUNT";
export const GET_OPEN_ACCOUNT = "GET_OPEN_ACCOUNT";

// View
export const GET_SINGLE_ACCOUNT = "GET_SINGLE_ACCOUNT";
export const GET_SINGLE_ACCOUNT_SUCCESS = "GET_SINGLE_ACCOUNT_SUCCESS";
export const CLEAR_SINGLE_ACCOUNT = "CLEAR_SINGLE_ACCOUNT";

// New
export const HANDLE_CHANGE_ACCOUNT = "HANDLE_CHANGE_ACCOUNT";
export const SUBMIT_ACCOUNT = "SUBMIT_ACCOUNT";
export const CLEAR_ACCOUNT_FORM = "CLEAR_ACCOUNT_FORM";
export const SUBMIT_ACCOUNT_SUCCESS = "SUBMIT_ACCOUNT_SUCCESS";
export const SUBMIT_ACCOUNT_ERROR = "SUBMIT_ACCOUNT_ERROR";

// Edit
export const START_ACCOUNT_EDIT = "START_ACCOUNT_EDIT";
export const SUBMIT_EDIT_ACCOUNT = "SUBMIT_EDIT_ACCOUNT";

// Notes
export const ADD_NOTE_ACCOUNT = "ADD_NOTE_ACCOUNT";
export const ADD_NOTE_ACCOUNT_SUCCESS = "ADD_NOTE_ACCOUNT_SUCCESS";
export const ADD_NOTE_ACCOUNT_FAILURE = "ADD_NOTE_ACCOUNT_FAILURE";

// Delete
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_FAILURE = "DELETE_ACCOUNT_FAILURE";

// Set Active
export const SET_ACCOUNT_ACTIVE = "SET_ACCOUNT_ACTIVE";
export const SET_ACCOUNT_ACTIVE_SUCCESS = "SET_ACCOUNT_ACTIVE_SUCCESS";
export const SET_ACCOUNT_ACTIVE_FAILURE = "SET_ACCOUNT_ACTIVE_FAILURE";

// Transfer
export const TRANSFER_ACCOUNT = "TRANSFER_ACCOUNT";
export const TRANSFER_ACCOUNT_SUCCESS = "TRANSFER_ACCOUNT_SUCCESS";
export const TRANSFER_ACCOUNT_FAILURE = "TRANSFER_ACCOUNT_FAILURE";
