/**
 * Account Actions
 */
export const ACCOUNT_LIST_DROPDOWN = "ACCOUNT_LIST_DROPDOWN";
export const TOGGLE_ACCOUNT_SUMMARY = "TOGGLE_ACCOUNT_SUMMARY";
export const CHANGE_ACCOUNT_LIST_VIEW = "CHANGE_ACCOUNT_LIST_VIEW";
export const GET_ACCOUNT_FAILURE = "GET_ACCOUNT_FAILURE";
export const GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS";
export const GET_ALL_ACCOUNT = "GET_ALL_ACCOUNT";
export const GET_MY_ACCOUNT = "GET_MY_ACCOUNT";
export const GET_OPEN_ACCOUNT = "GET_OPEN_ACCOUNT";
