/**
 * Customer Actions
 */
// List
export const CUSTOMER_LIST_DROPDOWN = "CUSTOMER_LIST_DROPDOWN";
export const CHANGE_CUSTOMER_LIST_VIEW = "CHANGE_CUSTOMER_LIST_VIEW";
export const GET_CUSTOMER_FAILURE = "GET_CUSTOMER_FAILURE";
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";
export const GET_ALL_CUSTOMER = "GET_ALL_CUSTOMER";
export const GET_MY_CUSTOMER = "GET_MY_CUSTOMER";
export const GET_OPEN_CUSTOMER = "GET_OPEN_CUSTOMER";

// View
export const GET_SINGLE_CUSTOMER = "GET_SINGLE_CUSTOMER";
export const GET_SINGLE_CUSTOMER_SUCCESS = "GET_SINGLE_CUSTOMER_SUCCESS";
export const CLEAR_SINGLE_CUSTOMER = "CLEAR_SINGLE_CUSTOMER";

// New
export const HANDLE_CHANGE_CUSTOMER = "HANDLE_CHANGE_CUSTOMER";
export const SUBMIT_CUSTOMER = "SUBMIT_CUSTOMER";
export const CLEAR_CUSTOMER_FORM = "CLEAR_CUSTOMER_FORM";
export const SUBMIT_CUSTOMER_SUCCESS = "SUBMIT_CUSTOMER_SUCCESS";
export const SUBMIT_CUSTOMER_ERROR = "SUBMIT_CUSTOMER_ERROR";
