/**
 * Customer Actions
 */
export const CUSTOMER_LIST_DROPDOWN = "CUSTOMER_LIST_DROPDOWN";
export const TOGGLE_CUSTOMER_SUMMARY = "TOGGLE_CUSTOMER_SUMMARY";
export const CHANGE_CUSTOMER_LIST_VIEW = "CHANGE_CUSTOMER_LIST_VIEW";
export const GET_CUSTOMER_FAILURE = "GET_CUSTOMER_FAILURE";
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";
export const GET_ALL_CUSTOMER = "GET_ALL_CUSTOMER";
export const GET_MY_CUSTOMER = "GET_MY_CUSTOMER";
export const GET_OPEN_CUSTOMER = "GET_OPEN_CUSTOMER";
