/**
 * Deal Actions
 */

// List
export const DEAL_LIST_DROPDOWN = "DEAL_LIST_DROPDOWN";
export const TOGGLE_DEAL_SUMMARY = "TOGGLE_DEAL_SUMMARY";
export const CHANGE_DEAL_LIST_VIEW = "CHANGE_DEAL_LIST_VIEW";
export const GET_DEAL_FAILURE = "GET_DEAL_FAILURE";
export const GET_DEAL_SUCCESS = "GET_DEAL_SUCCESS";
export const GET_ALL_DEAL = "GET_ALL_DEAL";
export const GET_MY_DEAL = "GET_MY_DEAL";
export const GET_OPEN_DEAL = "GET_OPEN_DEAL";
export const GET_CLOSED_DEAL = "GET_CLOSED_DEAL";
export const GET_WON_DEAL = "GET_WON_DEAL";

// List Summary
export const GET_DEAL_SUMMARY = "GET_DEAL_SUMMARY";
export const GET_DEAL_SUMMARY_SUCCESS = "GET_DEAL_SUMMARY_SUCCESS";
export const GET_DEAL_SUMMARY_FAILURE = "GET_DEAL_SUMMARY_FAILURE";

// View
export const GET_SINGLE_DEAL = "GET_SINGLE_DEAL";
export const GET_SINGLE_DEAL_SUCCESS = "GET_SINGLE_DEAL_SUCCESS";
export const CLEAR_SINGLE_DEAL = "CLEAR_SINGLE_DEAL";

// New
export const HANDLE_CHANGE_DEAL = "HANDLE_CHANGE_DEAL";
export const SUBMIT_DEAL = "SUBMIT_DEAL";
export const CLEAR_DEAL_FORM = "CLEAR_DEAL_FORM";
export const SUBMIT_DEAL_SUCCESS = "SUBMIT_DEAL_SUCCESS";
export const SUBMIT_DEAL_ERROR = "SUBMIT_DEAL_ERROR";
