/**
 * Lead Actions
 */

// List
export const LEAD_LIST_DROPDOWN = "LEAD_LIST_DROPDOWN";
export const TOGGLE_LEAD_SUMMARY = "TOGGLE_LEAD_SUMMARY";
export const CHANGE_LEAD_LIST_VIEW = "CHANGE_LEAD_LIST_VIEW";
export const GET_LEAD_FAILURE = "GET_LEAD_FAILURE";
export const GET_LEAD_SUCCESS = "GET_LEAD_SUCCESS";
export const GET_ALL_LEAD = "GET_ALL_LEAD";
export const GET_MY_LEAD = "GET_MY_LEAD";
export const GET_OPEN_LEAD = "GET_OPEN_LEAD";
export const GET_HOT_LEAD = "GET_HOT_LEAD";
export const GET_COLD_LEAD = "GET_COLD_LEAD";

// List Summary
export const GET_LEAD_SUMMARY = "GET_LEAD_SUMMARY";
export const GET_LEAD_SUMMARY_SUCCESS = "GET_LEAD_SUMMARY_SUCCESS";
export const GET_LEAD_SUMMARY_FAILURE = "GET_LEAD_SUMMARY_FAILURE";

// View
export const GET_SINGLE_LEAD = "GET_SINGLE_LEAD";
export const GET_SINGLE_LEAD_SUCCESS = "GET_SINGLE_LEAD_SUCCESS";
export const CLEAR_SINGLE_LEAD = "CLEAR_SINGLE_LEAD";
