/**
 * Lead Actions
 */

// List
export const LEAD_LIST_DROPDOWN = "LEAD_LIST_DROPDOWN";
export const TOGGLE_LEAD_SUMMARY = "TOGGLE_LEAD_SUMMARY";
export const CHANGE_LEAD_LIST_VIEW = "CHANGE_LEAD_LIST_VIEW";
export const GET_LEAD_FAILURE = "GET_LEAD_FAILURE";
export const GET_LEAD_SUCCESS = "GET_LEAD_SUCCESS";
export const GET_ALL_LEAD = "GET_ALL_LEAD";
export const GET_MY_LEAD = "GET_MY_LEAD";
export const GET_OPEN_LEAD = "GET_OPEN_LEAD";
export const GET_HOT_LEAD = "GET_HOT_LEAD";
export const GET_COLD_LEAD = "GET_COLD_LEAD";

// List Summary
export const GET_LEAD_SUMMARY = "GET_LEAD_SUMMARY";
export const GET_LEAD_SUMMARY_SUCCESS = "GET_LEAD_SUMMARY_SUCCESS";
export const GET_LEAD_SUMMARY_FAILURE = "GET_LEAD_SUMMARY_FAILURE";

// View
export const GET_SINGLE_LEAD = "GET_SINGLE_LEAD";
export const GET_SINGLE_LEAD_SUCCESS = "GET_SINGLE_LEAD_SUCCESS";
export const CLEAR_SINGLE_LEAD = "CLEAR_SINGLE_LEAD";

// New
export const HANDLE_CHANGE_NEW_LEAD = "HANDLE_CHANGE_NEW_LEAD";
export const SUBMIT_NEW_LEAD = "SUBMIT_NEW_LEAD";
export const CLEAR_NEW_LEAD = "CLEAR_NEW_LEAD";
export const NEW_LEAD_SUCCESS = "NEW_LEAD_SUCCESS";
export const NEW_LEAD_ERROR = "NEW_LEAD_ERROR";

// Convert Lead
export const HANDLE_CONVERT_MODAL = "HANDLE_CONVERT_MODAL";
export const HANDLE_SUCCESS_CONVERT_MODAL = "HANDLE_SUCCESS_CONVERT_MODAL";
export const HANDLE_CHANGE_CONVERT_LEAD = "HANDLE_CHANGE_CONVERT_LEAD";
export const CONVERT_LEAD = "CONVERT_LEAD";
export const CONVERT_LEAD_SUCCESS = "CONVERT_LEAD_SUCCESS";
export const CONVERT_LEAD_FAILURE = "CONVERT_LEAD_FAILURE";
export const UNMOUNT_CONVERT_LEAD = "UNMOUNT_CONVERT_LEAD";

// Edit
export const START_LEAD_EDIT = "START_LEAD_EDIT";
export const SUBMIT_EDIT_LEAD = "SUBMIT_EDIT_LEAD";
