/**
 * Calendar Actions
 */
export const GET_ALL_EVENTS = "GET_ALL_EVENTS";
export const GET_MY_EVENTS = "GET_MY_EVENTS";
export const CHANGE_DAY_VIEW = "CHANGE_DAY_VIEW";
export const CHANGE_EVENT_VIEW = "CHANGE_EVENT_VIEW";
export const CHANGE_CALENDAR_VIEW = "CHANGE_CALENDAR_VIEW";
export const SHOW_SELECTED_SLOT = "SHOW_SELECTED_SLOT";
export const HIDE_SELECTED_SLOT = "HIDE_SELECTED_SLOT";
export const SHOW_SELECTED_EVENT = "SHOW_SELECTED_EVENT";
export const SHOW_CREATE_EVENT = "SHOW_CREATE_EVENT";
export const HIDE_CREATE_EVENT = "HIDE_CREATE_EVENT";
export const SHOW_UPDATE_EVENT = "SHOW_UPDATE_EVENT";
