/**
 * Report Actions
 */
export const CHANGE_REPORT_VIEW = "CHANGE_REPORT_VIEW";
export const OPEN_NESTED_VIEW = "OPEN_NESTED_VIEW";

export const REPORT_ON_DATES_CHANGE = "REPORT_ON_DATES_CHANGE";
export const REPORT_ON_FOCUS_CHANGE = "REPORT_ON_FOCUS_CHANGE";
export const REPORT_RESET_DATES = "REPORT_RESET_DATES";

export const GET_REPORT_FAILURE = "GET_REPORT_FAILURE";

// Deal Report
export const GET_DEAL_REPORT = "GET_DEAL_REPORT";
export const GET_DEAL_REPORT_SUCCESS = "GET_DEAL_REPORT_SUCCESS";

// Lead Report
export const GET_LEAD_REPORT = "GET_LEAD_REPORT";
export const GET_LEAD_REPORT_SUCCESS = "GET_LEAD_REPORT_SUCCESS";

// Individual Report
export const GET_INDIVIDUAL_REPORT = "GET_INDIVIDUAL_REPORT";
export const GET_INDIVIDUAL_REPORT_SUCCESS = "GET_INDIVIDUAL_REPORT_SUCCESS";
export const ON_CHANGE_STAFF_SELECT = "ON_CHANGE_STAFF_SELECT";
