/**
 * Report Actions
 */
export const GET_REPORT_FAILURE = "GET_REPORT_FAILURE";

// Deal Report
export const GET_DEALS_BY_OWNER = "GET_DEALS_BY_OWNER";
export const GET_DEALS_BY_OWNER_SUCCESS = "GET_DEALS_BY_OWNER_SUCCESS";

export const GET_DEALS_BY_TYPE = "GET_DEALS_BY_TYPE";
export const GET_DEALS_BY_TYPE_SUCCESS = "GET_DEALS_BY_TYPE_SUCCESS";

export const GET_DEALS_PIPELINE = "GET_DEALS_PIPELINE";
export const GET_DEALS_PIPELINE_SUCCESS = "GET_DEALS_PIPELINE_SUCCESS";

// Lead Report
export const GET_LEAD_REPORT = "GET_LEAD_REPORT";
export const GET_LEAD_REPORT_SUCCESS = "GET_LEAD_REPORT_SUCCESS";

// Individual Report
export const GET_INDIVIDUAL_REPORT = "GET_INDIVIDUAL_REPORT";
export const GET_INDIVIDUAL_REPORT_SUCCESS = "GET_INDIVIDUAL_REPORT_SUCCESS";
export const ON_CHANGE_STAFF_SELECT = "ON_CHANGE_STAFF_SELECT";
