export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGIN_USER_RESENT_EMAIL = "LOGIN_USER_RESENT_EMAIL";
export const LOGIN_USER_RESENT_EMAIL_SUCCESS =
  "LOGIN_USER_RESENT_EMAIL_SUCCESS";
export const LOGIN_USER_RESENT_EMAIL_FAILURE =
  "LOGIN_USER_RESENT_EMAIL_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";
export const LOGIN_USER_RESET_PASSWORD = "LOGIN_USER_RESET_PASSWORD";
export const LOGIN_USER_RESET_PASSWORD_SUCCESS =
  "LOGIN_USER_RESET_PASSWORD_SUCCESS";
export const LOGIN_USER_RESET_PASSWORD_FAILURE =
  "LOGIN_USER_RESET_PASSWORD_FAILURE";

export const USER_RIGHTS = "USER_RIGHTS";
export const USER_RIGHTS_SUCCESS = "USER_RIGHTS_SUCCESS";
export const USER_RIGHTS_FAILURE = "USER_RIGHTS_FAILURE";
